version: '3'
services:
  bark-server:
    image: finab/bark-server:latest
    container_name: bark-server
    restart: always
    volumes:
      - $HOME/docker/bark/data:/data
    ports:
      - "3002:8080"