services:
  nacos:
    image: ${NACOS_IMAGE_REPOSITORY}:${NACOS_IMAGE_VERSION}
    container_name: nacos-server
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=${MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_PORT=${MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_DB_NAME=${MYSQL_SERVICE_DB_NAME}
      - MYSQL_SERVICE_USER=${MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${MYSQL_SERVICE_PASSWORD}
      - JVM_XMS=${JVM_XMS}
      - JVM_XMX=${JVM_XMX}
      - JVM_XMN=${JVM_XMN}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
    volumes:
      - ./config/custom.properties:/home/nacos/init.d/custom.properties